### ISSUE TITLE
h5py 3.7.0 ARM not building

### ISSUE THREAD

**Issue by kmuehlbauer** [conda-forge/h5py-feedstock#115]
### Comment:

Currently the ARM builds still fail in CI, see https://github.com/conda-forge/h5py-feedstock/pull/114.

Maintainers merged the above PR to at least move forward with the green builds (linux x64, osx, windows).

Adding a list with the failing architectures after processing of https://github.com/conda-forge/h5py-feedstock/runs/7074185121.

**Comment by kmuehlbauer** [comment]
Failing:

- linux aarch64 builds
- linux ppc64le builds
- osx arm64 builds

**Comment by hmaarrfk** [comment]
Ultimately, it seems that the cross compilation patch needs to be updated.

A clue can be followed from: https://github.com/conda-forge/h5py-feedstock/blob/main/recipe/osx-arm64.diff

the reason is that different c level `defines` get enabled and disabled for h5py depending on the associated compilation options for hdf5
