### ISSUE TITLE
h5py is running against HDF5 1.10.5 when it was built against 1.10.4

### ISSUE THREAD

**Issue by jan-janssen** [conda-forge/h5py-feedstock#54]
Is it possible to pin HDF5 ? Otherwise I get the following error message when I upgrade. 

```
UserWarning: h5py is running against HDF5 1.10.5 when it was built against 1.10.4, this may cause problems
  '{0}.{1}.{2}'.format(*version.hdf5_built_version_tuple)
```

**Comment by ocefpaf** [comment]
It is pinned. It may be that something is not OK with the HDF5 new build strings for the `mpi` variants.

**Comment by Marietto2008** [comment]
C:\Users\marietto2020\Desktop\MMD\OpenMMD\OpenMMD 1.0\3d-pose-baseline-vmd
(tensorflow) λ openposeto3d

´╗┐es (40 sloc) 1.62 KB
"´╗┐es" non è riconosciuto come comando interno o esterno,
 un programma eseguibile o un file batch.
Please input the path of result from OpenPose Execution: JSON folder
Input is limited to English characters and numbers.
Ôûáthe path of result from OpenPose Execution (JSON folder): json
--------------
The max number of people in your video.
If no input and press Enter, the number of be set to default: 1 person.
The max number of people in your video: 1
--------------
If you want the detailed information of GIF, input yes.
If no input and press Enter, the generation setting of GIF will be set to default.
warn If you input warn, then no GIF will be generated.
the detailed information[yes/no/warn]: yes
C:\Users\marietto2020\.conda\envs\tensorflow\lib\site-packages\h5py\__init__.py:40: UserWarning: h5py is running against HDF5 1.10.5 when it was built against 1.10.4, this may cause problems
  '{0}.{1}.{2}'.format(*version.hdf5_built_version_tuple)
Warning! ***HDF5 library version mismatched error***
The HDF5 header files used to compile this application do not match
the version used by the HDF5 library to which this application is linked.
Data corruption or segmentation faults may occur if the application continues.
This can happen when an application was compiled by one version of HDF5 but
linked with a different version of static or shared HDF5 library.
You should recompile the application or check your shared library related
settings such as 'LD_LIBRARY_PATH'.
You can, at your own risk, disable this warning by setting the environment
variable 'HDF5_DISABLE_VERSION_CHECK' to a value of '1'.
Setting it to 2 or higher will suppress the warning messages totally.
Headers are 1.10.4, library is 1.10.5
        SUMMARY OF THE HDF5 CONFIGURATION
        =================================

General Information:
-------------------
                   HDF5 Version: 1.10.5
                  Configured on: 2019-03-04
                  Configured by: Visual Studio 14 2015 Win64
                    Host system: Windows-10.0.17763
              Uname information: Windows
                       Byte sex: little-endian
             Installation point: C:/Program Files/HDF5

Compiling Options:
------------------
                     Build Mode:
              Debugging Symbols:
                        Asserts:
                      Profiling:
             Optimization Level:

Linking Options:
----------------
                      Libraries:
  Statically Linked Executables: OFF
                        LDFLAGS: /machine:x64
                     H5_LDFLAGS:
                     AM_LDFLAGS:
                Extra libraries:
                       Archiver:
                         Ranlib:

Languages:
----------
                              C: yes
                     C Compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe 19.0.24218.1
                       CPPFLAGS:
                    H5_CPPFLAGS:
                    AM_CPPFLAGS:
                         CFLAGS:  /DWIN32 /D_WINDOWS /W3
                      H5_CFLAGS:
                      AM_CFLAGS:
               Shared C Library: YES
               Static C Library: YES

                        Fortran: OFF
               Fortran Compiler:
                  Fortran Flags:
               H5 Fortran Flags:
               AM Fortran Flags:
         Shared Fortran Library: YES
         Static Fortran Library: YES

                            C++: ON
                   C++ Compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe 19.0.24218.1
                      C++ Flags: /DWIN32 /D_WINDOWS /W3 /GR /EHsc
                   H5 C++ Flags:
                   AM C++ Flags:
             Shared C++ Library: YES
             Static C++ Library: YES

                            JAVA: OFF
                   JAVA Compiler:

Features:
---------
                   Parallel HDF5: OFF
Parallel Filtered Dataset Writes:
              Large Parallel I/O:
              High-level library: ON
                    Threadsafety: OFF
             Default API mapping: v110
  With deprecated public symbols: ON
          I/O filters (external):  DEFLATE DECODE ENCODE
                             MPE:
                      Direct VFD:
                         dmalloc:
  Packages w/ extra debug output:
                     API Tracing: OFF
            Using memory checker: OFF
 Memory allocation sanity checks: OFF
          Function Stack Tracing: OFF
       Strict File Format Checks: OFF
    Optimization Instrumentation:
Bye...

**Comment by tatianapg** [comment]
(April 16 2020)
Hi, I am working with python 3.7.
I had the same problem "UserWa ing: h5py is running against HDF5 1.10.5 when it was built against 1.10.4"
In my case I tried: conda uninstall/install hdf5, then conda uninstall/install h5py.  They did nor work.
Finally I followed this suggestion (https://github.com/conda-forge/h5py-feedstock/issues/39):
"The error disappears when using channel anaconda...
...
conda install -c anaconda keras
"
I had my environment created, so I only executed "conda install -c anaconda keras"
I got my environment with tensorflow. However I had a warning, when I typed: import tensorflow as tf
"
FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecate
in a future version of numpy, it will be understood as (type, (1,)) / '(1,)ty
"
The second time I typed: import tensorflow as tf, I got the version 1.14.0.
I have not done any tasks with tensorflow yet to verify if the warning brings problems.

**Comment by dhruvsakalley** [comment]
Same problem with python 3.6
Trying to get together a conda environment with transfomers/tensorflow-gpu 2.1/pytorch/ allennlp and it's not happening because of this error.
here is the conda env export -f tx36.yml

`
name: tx36
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _tflow_select=2.1.0=gpu
  - absl-py=0.9.0=py36_0
  - arrow-cpp=0.15.1=py36h47fa567_6
  - astor=0.8.0=py36_0
  - awswrangler=0.3.1=py_0
  - blas=1.0=mkl
  - blinker=1.4=py36_0
  - boost-cpp=1.69.0=h6a4c333_1000
  - boto=2.49.0=py36_0
  - boto3=1.13.6=pyh9f0ad1d_0
  - botocore=1.16.6=pyh9f0ad1d_0
  - brotli=1.0.7=he025d50_1001
  - bzip2=1.0.8=hfa6e2cd_2
  - c-ares=1.15.0=h2fa13f4_1001
  - ca-certificates=2020.4.5.1=hecc5488_0
  - cachetools=3.1.1=py_0
  - certifi=2020.4.5.1=py36h9f0ad1d_0
  - cffi=1.14.0=py36h7a1dbc1_0
  - chardet=3.0.4=py36_1003
  - click=7.1.2=py_0
  - cryptography=2.9.2=py36h7a1dbc1_0
  - cudatoolkit=10.1.243=h74a9793_0
  - cudnn=7.6.5=cuda10.1_0
  - docutils=0.15.2=py36_0
  - double-conversion=3.1.5=h6538335_2
  - freetype=2.9.1=ha9979f8_1
  - fsspec=0.7.3=py_0
  - gast=0.2.2=py36_0
  - gensim=3.8.0=py36hf9181ef_0
  - gflags=2.2.2=he025d50_1002
  - glog=0.4.0=h0174b99_3
  - google-api-core=1.17.0=py36h21ff451_0
  - google-auth=1.14.1=py_0
  - google-auth-oauthlib=0.4.1=py_2
  - google-cloud-core=1.3.0=py_0
  - google-cloud-storage=1.28.0=py_0
  - google-pasta=0.2.0=py_0
  - google-resumable-media=0.5.0=py_1
  - googleapis-common-protos=1.51.0=py36h21ff451_2
  - grpc-cpp=1.26.0=h9f84659_0
  - grpcio=1.27.2=py36h351948d_0
  - h5py=2.10.0=py36h5e291fa_0
  - hdf5=1.10.4=h7ebc959_0
  - icc_rt=2019.0.0=h0cc432a_1
  - idna=2.9=py_1
  - intel-openmp=2020.0=166
  - jmespath=0.9.5=py_0
  - jpeg=9b=hb83a4c4_2
  - keras-applications=1.0.8=py_0
  - keras-preprocessing=1.1.0=py_1
  - libboost=1.67.0=hd9e427e_4
  - libpng=1.6.37=h2a8f88b_0
  - libprotobuf=3.11.2=h1a1b453_0
  - libtiff=4.1.0=h56a325e_0
  - lz4-c=1.8.3=he025d50_1001
  - markdown=3.1.1=py36_0
  - mkl=2020.0=166
  - mkl-service=2.3.0=py36hb782905_0
  - mkl_fft=1.0.15=py36h14836fe_0
  - mkl_random=1.1.0=py36h675688f_0
  - ninja=1.9.0=py36h74a9793_0
  - numpy=1.18.1=py36h93ca92e_0
  - numpy-base=1.18.1=py36hc3f5095_1
  - oauthlib=3.1.0=py_0
  - olefile=0.46=py36_0
  - openssl=1.1.1g=he774522_0
  - opt_einsum=3.1.0=py_0
  - pandas=1.0.3=py36hcc50265_1
  - pg8000=1.15.2=py_0
  - pillow=7.1.2=py36hcc1f983_0
  - pip=20.0.2=py36_3
  - pyarrow=0.15.1=py36h47e9c7a_0
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.20=py_0
  - pyjwt=1.7.1=py36_0
  - pymysql=0.9.3=py_0
  - pyopenssl=19.1.0=py36_0
  - pyreadline=2.1=py36_1
  - pysocks=1.7.1=py36_0
  - python=3.6.10=h9f7ef89_2
  - python-dateutil=2.8.1=py_0
  - python_abi=3.6=1_cp36m
  - pytorch=1.5.0=py3.6_cuda101_cudnn7_0
  - pytz=2020.1=pyh9f0ad1d_0
  - re2=2020.05.01=vc14ha925a31_0
  - requests=2.23.0=py36_0
  - requests-oauthlib=1.3.0=py_0
  - rsa=4.0=py_0
  - s3fs=0.4.2=py_0
  - s3transfer=0.3.3=py36h9f0ad1d_1
  - scipy=1.4.1=py36h9439919_0
  - scramp=1.1.1=py_0
  - setuptools=46.1.3=py36_0
  - six=1.14.0=py36_0
  - smart_open=2.0.0=py_0
  - snappy=1.1.8=he025d50_1
  - sqlite=3.31.1=h2a8f88b_1
  - tenacity=6.2.0=py36h9f0ad1d_0
  - tensorboard=2.1.0=py3_0
  - tensorflow=2.1.0=gpu_py36h3346743_0
  - tensorflow-base=2.1.0=gpu_py36h55f5790_0
  - tensorflow-estimator=2.1.0=pyhd54b08b_0
  - tensorflow-gpu=2.1.0=h0d30ee6_0
  - termcolor=1.1.0=py36_1
  - thrift-cpp=0.11.0=h1ebf3fd_3
  - tk=8.6.8=hfa6e2cd_0
  - torchvision=0.6.0=py36_cu101
  - uriparser=0.9.3=he025d50_1
  - vc=14.1=h0510ff6_4
  - vs2015_runtime=14.16.27012=hf0eaf9b_1
  - wheel=0.34.2=py36_0
  - win_inet_pton=1.1.0=py36_0
  - wincertstore=0.2=py36h7fe50ca_0
  - wrapt=1.12.1=py36he774522_1
  - xz=5.2.5=h62dcd97_0
  - zlib=1.2.11=h62dcd97_4
  - zstd=1.3.7=h508b16e_0
  - pip:
    - alabaster==0.7.12
    - allennlp==0.9.0
    - atomicwrites==1.4.0
    - attrs==19.3.0
    - babel==2.8.0
    - blis==0.2.4
    - colorama==0.4.3
    - conllu==1.3.1
    - cycler==0.10.0
    - cymem==2.0.3
    - dataclasses==0.7
    - editdistance==0.5.3
    - filelock==3.0.12
    - flaky==3.6.1
    - flask==1.1.2
    - flask-cors==3.0.8
    - ftfy==5.7
    - future==0.18.2
    - gevent==20.5.0
    - greenlet==0.4.15
    - imagesize==1.2.0
    - importlib-metadata==1.6.0
    - itsdangerous==1.1.0
    - jinja2==2.11.2
    - joblib==0.14.1
    - jsonpickle==1.4.1
    - keras==2.3.1
    - kiwisolver==1.2.0
    - markupsafe==1.1.1
    - matplotlib==3.2.1
    - more-itertools==8.2.0
    - murmurhash==1.0.2
    - nltk==3.5
    - numpydoc==0.9.2
    - overrides==2.8.0
    - packaging==20.3
    - parsimonious==0.8.1
    - plac==0.9.6
    - pluggy==0.13.1
    - preshed==2.0.1
    - protobuf==3.11.3
    - py==1.8.1
    - pygments==2.6.1
    - pyparsing==2.4.7
    - pytest==5.4.2
    - pytorch-pretrained-bert==0.6.2
    - pytorch-transformers==1.1.0
    - pyyaml==5.3.1
    - regex==2020.5.7
    - responses==0.10.14
    - sacremoses==0.0.43
    - scikit-learn==0.22.2.post1
    - sentencepiece==0.1.86
    - seqeval==0.0.12
    - simpletransformers==0.28.0
    - snowballstemmer==2.0.0
    - spacy==2.1.9
    - sphinx==3.0.3
    - sphinxcontrib-applehelp==1.0.2
    - sphinxcontrib-devhelp==1.0.2
    - sphinxcontrib-htmlhelp==1.0.3
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.3
    - sphinxcontrib-serializinghtml==1.1.4
    - sqlparse==0.3.1
    - srsly==1.0.2
    - tensorboardx==2.0
    - thinc==7.0.8
    - tokenizers==0.7.0
    - tqdm==4.46.0
    - transformers==2.9.0
    - unidecode==1.1.1
    - urllib3==1.25.9
    - wasabi==0.6.0
    - wcwidth==0.1.9
    - werkzeug==1.0.1
    - word2number==1.1
    - zipp==3.1.0
prefix: D:\Anaconda3\envs\tx36
`

Here's the error I get after python >>import transformers

D:\Anaconda3\envs\tx36\lib\site-packages\h5py\__init__.py:40: UserWarning: h5py is running against HDF5 1.10.5 when it was built against 1.10.4, this may cause problems
  '{0}.{1}.{2}'.format(*version.hdf5_built_version_tuple)
Warning! ***HDF5 library version mismatched error***
The HDF5 header files used to compile this application do not match
the version used by the HDF5 library to which this application is linked.
Data corruption or segmentation faults may occur if the application continues.
This can happen when an application was compiled by one version of HDF5 but
linked with a different version of static or shared HDF5 library.
You should recompile the application or check your shared library related
settings such as 'LD_LIBRARY_PATH'.
You can, at your own risk, disable this warning by setting the environment
variable 'HDF5_DISABLE_VERSION_CHECK' to a value of '1'.
Setting it to 2 or higher will suppress the warning messages totally.
Headers are 1.10.4, library is 1.10.5
        SUMMARY OF THE HDF5 CONFIGURATION
        =================================

General Information:
-------------------
                   HDF5 Version: 1.10.5
                  Configured on: 2019-03-04
                  Configured by: Visual Studio 14 2015 Win64
                    Host system: Windows-10.0.17763
              Uname information: Windows
                       Byte sex: little-endian
             Installation point: C:/Program Files/HDF5

Compiling Options:
------------------
                     Build Mode:
              Debugging Symbols:
                        Asserts:
                      Profiling:
             Optimization Level:

Linking Options:
----------------
                      Libraries:
  Statically Linked Executables: OFF
                        LDFLAGS: /machine:x64
                     H5_LDFLAGS:
                     AM_LDFLAGS:
                Extra libraries:
                       Archiver:
                         Ranlib:

Languages:
----------
                              C: yes
                     C Compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe 19.0.24218.1
                       CPPFLAGS:
                    H5_CPPFLAGS:
                    AM_CPPFLAGS:
                         CFLAGS:  /DWIN32 /D_WINDOWS /W3
                      H5_CFLAGS:
                      AM_CFLAGS:
               Shared C Library: YES
               Static C Library: YES

                        Fortran: OFF
               Fortran Compiler:
                  Fortran Flags:
               H5 Fortran Flags:
               AM Fortran Flags:
         Shared Fortran Library: YES
         Static Fortran Library: YES

                            C++: ON
                   C++ Compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe 19.0.24218.1
                      C++ Flags: /DWIN32 /D_WINDOWS /W3 /GR /EHsc
                   H5 C++ Flags:
                   AM C++ Flags:
             Shared C++ Library: YES
             Static C++ Library: YES

                            JAVA: OFF
                   JAVA Compiler:

Features:
---------
                   Parallel HDF5: OFF
Parallel Filtered Dataset Writes:
              Large Parallel I/O:
              High-level library: ON
                    Threadsafety: OFF
             Default API mapping: v110
  With deprecated public symbols: ON
          I/O filters (external):  DEFLATE DECODE ENCODE
                             MPE:
                      Direct VFD:
                         dmalloc:
  Packages w/ extra debug output:
                     API Tracing: OFF
            Using memory checker: OFF
 Memory allocation sanity checks: OFF
          Function Stack Tracing: OFF
       Strict File Format Checks: OFF
    Optimization Instrumentation:
Bye...

**Comment by kmuehlbauer** [comment]
@dhruvsakalley Looking at your package list, it seems you do not have any package from conda-forge channel. The h5py package as well as hdf5 are from defaults channel.

@jan-janssen If this still an issue for you, please provide more details.

**Comment by dhruvsakalley** [comment]
I think there is a conflict with tensorflow-gpu install, when conda installs from multiple channels it prefers to replace package from the most recent channel. I cannot get tensorflow, pytorch, allennlp to play well together for this reason in the same conda environment. But I understand this is beyond the scope of the h5py team

**Comment by xalphonseinbaraj** [comment]
you need uninstall h5py (pip uninstall h5py) then again install it (pip install h5py). Thats all . It worked

**Comment by fPkX6F1nGTX** [comment]
My solution was to use Python 3.7 instead of 3.6.9 (on Windows 10).

**Comment by DaudAhmad0303** [comment]
> you need uninstall h5py (pip uninstall h5py) then again install it (pip install h5py). Thats all . It worked

It Works 👍
